version: "3.9"

name: grpc-sample

services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - laravel-app
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend

  laravel-app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app_db
      DB_USERNAME: app_user
      DB_PASSWORD: app_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GRPC_USER_SERVICE_HOST: grpc-user-service:50051
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - grpc-user-service
    command: php-fpm
    ports:
      - "9000:9000"
    networks:
      - backend

  grpc-user-service:
    build:
      context: ./grpc-user-service
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./grpc-user-service:/app
      - ./contracts:/contracts
    environment:
      PORT: 50051
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: app_db
      DB_USER: app_user
      DB_PASSWORD: app_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "50051:50051"
      - "9464:9464"
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - backend

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  backend:
    driver: bridge
