#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';
$app->useEnvironmentPath(dirname(__DIR__));
$app->loadEnvironmentFrom('.env');

$status = $app->handleCommand(new ArgvInput);

exit($status);