<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/v1/user.proto

namespace User\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>user.v1.UserStatus</code>
 */
class UserStatus
{
    /**
     * Generated from protobuf enum <code>USER_STATUS_UNSPECIFIED = 0;</code>
     */
    const USER_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>USER_STATUS_ACTIVE = 1;</code>
     */
    const USER_STATUS_ACTIVE = 1;
    /**
     * Generated from protobuf enum <code>USER_STATUS_BLOCKED = 2;</code>
     */
    const USER_STATUS_BLOCKED = 2;

    private static $valueToName = [
        self::USER_STATUS_UNSPECIFIED => 'USER_STATUS_UNSPECIFIED',
        self::USER_STATUS_ACTIVE => 'USER_STATUS_ACTIVE',
        self::USER_STATUS_BLOCKED => 'USER_STATUS_BLOCKED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

